version: "3.8"

services:
  backend:
    build: ./backend
    expose:
      - "8000"

    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build: ./frontend
    expose:
      - "5173"

    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true
